### ISSUE TITLE
Add a template to solve AoC challenges

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/advent-of-code#11]
Solving an Advent of Code challenge requires a lot of repetition. To streamline the process of participating in AoC challenges, I want to create a set of scripts and workflows that automate repetitive tasks such as data retrieval and setting up the problem environment. This automation will help me focus on solving the challenges efficiently without the need to download inputs or set up boilerplate code repeatedly manually.

There are available solutions, and I'm most likely to get inspired by what the community did. Here are a few links to consider while working on this:

- https://github.com/ksmithut/advent_of_code_elixir_template
- https://github.com/mhanberg/advent-of-code-elixir-starter
- https://youtu.be/gpaV4bgEG-g?si=tDDgExjbc1HjeN_3

## Tasks 

- [ ] Create a script that automatically fetches the AoC problem statement for a given **day.** I would imagine that we save the prompt in a Markdown file at `/lib/AoC/prompts/YYYY/day_XX`.
- [ ] Automate downloading the personalized input data for my username. I would imagine that we save the prompt in a Markdown file at `/lib/AoC/inputs/YYYY/day_XX`.
- [ ] Create a script to generate a ready-to-use code template for solving challenges. 
    - [ ] The boilerplate should be used to solve the two parts and for unit testing. 
    - [ ] There should be an auto-include of the input loading within the file.
    - [ ] The script should be referenced in the proper section for the Livebook notes on AoC challenges.
