### ISSUE TITLE
Add all existing challenges from the AoC as issues on the repository

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/advent-of-code#7]
As I work on completing the challenges in the Advent of Code throughout the years, it'll provide a nice boost in confidence to close issues on the repository. 

To that end, I want to add all existing issues published throughout the years. However, this would be time-consuming and provide little to no benefit. But there's a way around this: I could create a script with Elixir (part of my Elixir journey) to crawl the AoC website and pull the data from 2015 to 2024.

I can automatically create issues, assign them to their milestones, and start working from there.

## Tasks

- [ ] Set up a development environment for Elixir to perform HTTP requests and JSON parsing (libraries available: HTTPoison, Jason, Floki)
- [ ] Define an automation to create an issue on this repository using the GitHub API
- [ ] Parse the data coming from the AoC website.
- [ ] Convert data from the AoC website as a GitHub issue on this repo.
- [ ] Add unit tests to the automation
- [ ] Create one issue using the automation with the proper labels + association with the correct milestone
- [ ] Document the script functionality and usage in the repository's README or a dedicated file for future reference.
