### ISSUE TITLE
Cache star progression data from the AoC

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/advent-of-code#9]
Create a caching mechanism to avoid redundant requests for star data from AoC, especially for completed days.

## Tasks

- [ ] Implement caching logic to store daily star data.
- [ ] Update the cache only for days not completed (both stars earned).
- [ ] Add a function to retrieve star data from the cache for rendering purposes.
